apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whitesource-renovate.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "whitesource-renovate.name" . }}
    helm.sh/chart: {{ include "whitesource-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "whitesource-renovate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "whitesource-renovate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.renovate.acceptAgreement }}
            - name: ACCEPT_AGREEMENT
              value: {{ .Values.renovate.acceptAgreement | quote }}
            {{- end }}
            {{- if .Values.renovate.licenseMode }}
            - name: LICENSE_MODE
              value: {{ .Values.renovate.licenseMode | quote }}
            {{- end }}
            {{- if .Values.renovate.licenseName }}
            - name: LICENSE_NAME
              value: {{ .Values.renovate.licenseName | quote }}
            {{- end }}
            {{- if .Values.renovate.renovatePlatform }}
            - name: RENOVATE_PLATFORM
              value: {{ .Values.renovate.renovatePlatform | quote }}
            {{- end }}
            {{- if .Values.renovate.renovateEndpoint }}
            - name: RENOVATE_ENDPOINT
              value: {{ .Values.renovate.renovateEndpoint | quote }}
            {{- end }}
            {{- if .Values.renovate.renovateToken }}
            - name: RENOVATE_TOKEN
              valueFrom:
                secretKeyRef:
                  secretName: {{ .Release.Name }}
                  key: renovateToken
            {{- end }}
            {{- if .Values.renovate.githubAppId }}
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  secretName: {{ .Release.Name }}
                  key: githubAppId
            {{- end }}
            {{- if .Values.renovate.githubAppKey }}
            - name: GITHUB_APP_KEY
              valueFrom:
                secretKeyRef:
                  secretName: {{ .Release.Name }}
                  key: githubAppKey
            {{- end }}
            {{- if .Values.renovate.githubComToken }}
            - name: GITHUB_COM_TOKEN
              valueFrom:
                secretKeyRef:
                  secretName: {{ .Release.Name }}
                  key: githubComToken
            {{- end }}
            {{- if .Values.renovate.webhookSecret }}
            - name: WEBHOOK_SECRET
              value: {{ .Values.renovate.webhookSecret | quote }}
            {{- end }}
            {{- if .Values.renovate.schedulerCron }}
            - name: SCHEDULER_CRON
              value: {{ .Values.renovate.schedulerCron | quote }}
            {{- end }}
            {{- if .Values.renovate.noNodeTlsVerify }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            {{- end }}
            {{- if .Values.renovate.noGitTlsVerify }}
            - name: GIT_SSL_NO_VERIFY
              value: 'true'
            {{- end }}
            {{- if .Values.renovate.renovateUserAgent }}
            - name: RENOVATE_USER_AGENT
              value: {{ .Values.renovate.renovateUserAgent | quote }}
            {{- end }}
            {{- if .Values.renovate.logLevel }}
            - name: LOG_LEVEL
              value: {{ .Values.renovate.logLevel | quote }}
            {{- end }}
            {{- if .Values.postgresql.enabled }}
            - name: PGHOST
              value: {{ template "whitesource-renovate.postgresql.fullname" . }}
            - name: PGUSER
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "whitesource-renovate.postgresql.fullname" . }}
                  key: postgresql-password
            - name: PGDATABASE
              value: {{ .Values.postgresql.postgresqlDatabase | quote }}
            {{- else }}
            {{- if .Values.renovate.postgresql.host }}
            - name: PGHOST
              value: {{ .Values.renovate.postgresql.host | quote }}
            {{- end }}
            {{- if .Values.renovate.postgresql.port }}
            - name: PGPORT
              value: {{ .Values.renovate.postgresql.port | quote }}
            {{- end }}
            {{- if .Values.renovate.postgresql.database }}
            - name: PGDATABASE
              value: {{ .Values.renovate.postgresql.database | quote }}
            {{- end }}
            {{- if .Values.renovate.postgresql.user }}
            - name: PGUSER
              value: {{ .Values.renovate.postgresql.user | quote }}
            {{- end }}
            {{- if .Values.renovate.postgresql.password }}
            - name: PGPASSWORD
              value: {{ .Values.renovate.postgresql.password | quote }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-config-js-volume
              mountPath: /usr/src/app/config.js
              subPath: config.js
            - name: {{ .Release.Name }}-npmrc-volume
              mountPath: /home/ubuntu/.npmrc
              subPath: .npmrc
            - name: {{ .Release.Name }}-cache-volume
              mountPath: /tmp/renovate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Release.Name }}-config-js-volume
          configMap:
            name: {{ .Release.Name }}-config-js
        - name: {{ .Release.Name }}-npmrc-volume
          secret:
            secretName: {{ .Release.Name }}-npmrc
        - name: {{ .Release.Name }}-cache-volume
          emptyDir: {}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
