apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-js
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "renovate-pro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.js: {{ .Values.renovate.config | quote }}
